#supplementary section
import numpy as np
asym_abs_pml_pml = np.loadtxt('./Num_center_pressure/asym_absPresdata_PML_PML_center.txt', skiprows=8)
asym_abs_pml_hard = np.loadtxt('./Num_center_pressure/asym_absPresdata_PML_Hard_center.txt', skiprows=8)
sym_abs_pml_pml = np.loadtxt('./Num_center_pressure/sym_absPresdata_PML_PML_center.txt', skiprows=8)
sym_abs_pml_hard = np.loadtxt('./Num_center_pressure/sym_absPresdata_PML_Hard_center.txt', skiprows=8)
# plt.figure()
# plt.plot(asym_abs_pml_hard[:,1])

fig, ax=plt.subplots(2,1, figsize=(14,10))
# plt.subplot(1,1,1)
ax[0].plot(asym_abs_pml_pml[:,0],asym_abs_pml_pml[:,1],  label='asym-(PML-PML) 2270 Hz', color='black', linewidth=2.5)
ax[0].plot(asym_abs_pml_hard[:,0], asym_abs_pml_hard[:,1], label='asym-(PML-Hard)', color='black', marker='o',markeredgecolor='black', linewidth=2.5)
ax[0].set_xlabel("x [m]", fontsize=16)
ax[0].set_ylabel("$|P|$", fontsize=16)
#plt.xlim((300, 3600))
ax[0].tick_params(labelsize=16, width=1.2)
ax[0].legend(fontsize=16)
ax[0].axvspan(0.73, 0.78, color='gray', alpha=0.2)
#.grid()
#plt.tight_layout()

#plt.subplot(2,1,1)
ax[1].plot(asym_abs_pml_pml[:,0],asym_abs_pml_pml[:,2],  label='asym-(PML-PML) 3000 Hz', color='black', linewidth=2.5)
ax[1].plot(asym_abs_pml_hard[:,0], asym_abs_pml_hard[:,2], label='asym-(PML-Hard)', color='black', marker='o',markeredgecolor='black', linewidth=2.5)
ax[1].set_xlabel("x [m]", fontsize=16)
ax[1].set_ylabel("$|P|$", fontsize=16)
ax[1].tick_params(labelsize=16, width=1.2)
ax[1].axvspan(0.73, 0.78, color='gray', alpha=0.2)
ax[1].legend(fontsize=16)
#plt.grid()
#plt.tight_layout()
###--------------------------------
fig, ax=plt.subplots(2,1, figsize=(14,10))
# plt.subplot(1,1,1)
ax[0].plot(sym_abs_pml_pml[:,0], sym_abs_pml_pml[:,1],  label='sym-(PML-PML) 2270 Hz', color='black', linewidth=2.5)
ax[0].plot(sym_abs_pml_hard[:,0], sym_abs_pml_hard[:,1], label='sym-(PML-Hard)', color='black', marker='o',markeredgecolor='black', linewidth=2.5)
ax[0].set_xlabel("x [m]", fontsize=16)
ax[0].set_ylabel("$|P|$", fontsize=16)
#plt.xlim((300, 3600))
ax[0].tick_params(labelsize=16, width=1.2)
ax[0].legend(fontsize=16)
ax[0].axvspan(0.73, 0.78, color='gray', alpha=0.2)
#.grid()
#plt.tight_layout()

#plt.subplot(2,1,1)
ax[1].plot(sym_abs_pml_pml[:,0],sym_abs_pml_pml[:,2],  label='sym-(PML-PML) 3000 Hz', color='black', linewidth=2.5)
ax[1].plot(sym_abs_pml_hard[:,0], sym_abs_pml_hard[:,2], label='sym-(PML-Hard)', color='black', marker='o',markeredgecolor='black', linewidth=2.5)
ax[1].set_xlabel("x [m]", fontsize=16)
ax[1].set_ylabel("$|P|$", fontsize=16)
ax[1].tick_params(labelsize=16, width=1.2)
ax[1].axvspan(0.73, 0.78, color='gray', alpha=0.2)
ax[1].legend(fontsize=16)

##------------
plt.figure(figsize=(14,5))
# plt.subplot(1,1,1)
plt.plot(sym_abs_pml_pml[:,0], sym_abs_pml_hard[:,1],  label='sym-(PML-Hard) 2270 Hz', color='black', linewidth=2.5)
plt.plot(sym_abs_pml_hard[:,0], sym_abs_pml_hard[:,2], label='sym-(PML-Hard) 3000 Hz', color='black', marker='o',markeredgecolor='black', linewidth=2.5)
plt.plot(asym_abs_pml_hard[:,0], asym_abs_pml_hard[:,1],  label='asym-(PML-Hard) 2270 Hz', color='grey', linewidth=2.5)
plt.plot(asym_abs_pml_hard[:,0], asym_abs_pml_hard[:,2], label='sym-(PML-Hard) 3000 Hz ', color='grey', marker='o',markeredgecolor='grey', linewidth=2.5)

plt.xlabel("x [m]", fontsize=16)
plt.ylabel("$|P|$", fontsize=16)
#plt.xlim((300, 3600))
plt.tick_params(labelsize=16, width=1.2)
plt.legend(fontsize=16)
plt.axvspan(0.73, 0.78, color='gray', alpha=0.2)
